Send unhandled exception error messages to `error_log()`.
ezsystems/ezpublish-legacy pull request #1459
Opened 2020-06-12 09:25 UTC by omh

Before PHP 7 fatal errors was written to whatever PHP's `error_log` was set to. In PHP 7 most errors are exceptions, so eZ ends up swallowing everything, including fatal errors, in it's default exception handler and logging to its own `var/log/error.log` file. This file is, by default, is *heavily* rotated after only 250KB. This means it's very easy to lose important error messages.

2020-12-09 12:59 UTC, guillaumelecerf requested changes

2020-12-09 12:59 UTC, guillaumelecerf commented on lib/ezutils/classes/ezexecution.php
> +        eZLog::write( msg, 'error.log' );
misssing \$ before `msg`

2020-12-17 10:03 UTC, omh commented on lib/ezutils/classes/ezexecution.php
> +        eZLog::write( msg, 'error.log' );
That's embarrassing 😱  Fixed now :)

2020-12-17 11:02 UTC, guillaumelecerf approved these changes

2020-12-17 14:52 UTC, glye approved these changes

2020-12-17 15:05 UTC, andrerom commented
@omh if possible rebase for 2019.03, as there are no longer any releases made from master.

2020-12-25 14:18 UTC, pkamps commented
I understand that you can easily miss a log message due to the heavy log rotation. Would it help to adjust the log rotation with following setting?

https://github.com/ezsystems/ezpublish-legacy/blob/2019.03/config.php-RECOMMENDED#L250

I don't like the idea to push the error message into 2 different channels (error_log and eZLog::write).

2021-01-13 09:41 UTC, omh commented
@pkamps what specifically is it that you do not like about pushing it to two different channels? Potential performance impact? (which I think should be negligible assuming your site isn't crashing _a lot_).

2021-02-02 15:58 UTC, pkamps commented
Hi,

sorry for the late reply.

The performance impact is probably very low.

All software solutions I worked with have different log channels for notice, warning, errors etc. 
But I haven't seen that software solutions typically duplicates each log message and sends them to 2 different endpoints (files in most cases or in your case error_log and eZLog::write).

If you really need to duplicate each message, it's probably cleaner to extend eZLog and allow it to send messages to 2 endpoints.

2021-05-11 11:44 UTC, omh commented
I'm no longer involved with ezpublish legacy so closing this.

2021-05-11 11:44 UTC, closed without merging